### ISSUE TITLE
Several specs fail

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/mechanical_turk#97] opened 2017-08-30 07:20 UTC
Assigning this rather non-atomic issue to @DorinevanderVlies so you can learn a bit more about MT. Aks me questions any time!

**Comment by DorinevanderVlies** [comment] 2017-08-30 08:30
Challenge accepted

**Comment by DorinevanderVlies** [comment] 2017-10-26 12:02
Closing as is duplicate of https://github.com/quintel/mechanical_turk/issues/100

**Closed by DorinevanderVlies** 2017-10-26 12:02 UTC
Labels: bug
