### ISSUE TITLE
Excess electricity should match total stored electricity

### ISSUE THREAD

**Issue by ChaelKruip** [quintel/mechanical_turk#141] opened 2020-02-12 15:52 UTC
```Failures:

  1) Flexibility Electricity Conservation Electricity should be conserved between excess production and storage
     Failure/Error: expect(@scenario.turk_excess_electricity_storage_sum.value).to be_within(0.000001).of(@scenario.turk_excess_electricity_from_production.value)
       expected 0.15746755202276427 to be within 1.0e-06 of 1.595989060279976
     # ./spec/flexibility/flexibility_spec.rb:348:in `block (4 levels) in <top (required)>'
```

This is more than a rounding error it seems. @marliekeverweij can you pick this up or reassign?

**Comment by michieldenhaan** [comment] 2020-02-13 08:13
This was probably caused by unexpected HV losses/surpluses due to the new heat module.  Should be fixed with: https://github.com/quintel/etengine/pull/1089

**Closed by michieldenhaan** 2020-02-13 08:13 UTC
Labels: bug
